/**
 * Error Code Constants
 *
 * Mirrors backend error codes from backend/src/common/enums/error-code.enum.ts
 * Used for centralized error handling and translation lookup.
 */

/**
 * All possible error codes from the backend API.
 * These codes are returned in the error.code field of API responses.
 */
export const ErrorCode = {
  // Authentication & Credentials
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Activation & Registration
  ACTIVATION_CODE_EXPIRED: 'ACTIVATION_CODE_EXPIRED',
  ACTIVATION_CODE_INVALID: 'ACTIVATION_CODE_INVALID',
  MAX_ATTEMPTS_EXCEEDED: 'MAX_ATTEMPTS_EXCEEDED',
  NO_PENDING_REGISTRATION: 'NO_PENDING_REGISTRATION',
  NO_PENDING_REGISTRATION_FOR_RESEND: 'NO_PENDING_REGISTRATION_FOR_RESEND',
  RESEND_RATE_LIMIT_EXCEEDED: 'RESEND_RATE_LIMIT_EXCEEDED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Session & Verification
  SESSION_REQUIRED: 'SESSION_REQUIRED',
  SESSION_INVALID: 'SESSION_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Generic Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',

  // User Management
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
  CANNOT_MODIFY_HIGHER_ROLE: 'CANNOT_MODIFY_HIGHER_ROLE',
  INVALID_ROLE_ASSIGNMENT: 'INVALID_ROLE_ASSIGNMENT',
  USER_ALREADY_DELETED: 'USER_ALREADY_DELETED',

  // OAuth - Generic
  INVALID_OAUTH_PROVIDER: 'INVALID_OAUTH_PROVIDER',
  OAUTH_AUTHENTICATION_FAILED: 'OAUTH_AUTHENTICATION_FAILED',
  OAUTH_INVALID_CODE: 'OAUTH_INVALID_CODE',

  // Google OAuth
  GOOGLE_TOKEN_INVALID: 'GOOGLE_TOKEN_INVALID',
  GOOGLE_TOKEN_EXPIRED: 'GOOGLE_TOKEN_EXPIRED',
  GOOGLE_NOT_CONFIGURED: 'GOOGLE_NOT_CONFIGURED',
  GOOGLE_EMAIL_NOT_VERIFIED: 'GOOGLE_EMAIL_NOT_VERIFIED',

  // GitHub OAuth
  GITHUB_CODE_INVALID: 'GITHUB_CODE_INVALID',
  GITHUB_CODE_EXPIRED: 'GITHUB_CODE_EXPIRED',
  GITHUB_NOT_CONFIGURED: 'GITHUB_NOT_CONFIGURED',
  GITHUB_EMAIL_NOT_VERIFIED: 'GITHUB_EMAIL_NOT_VERIFIED',
  GITHUB_API_ERROR: 'GITHUB_API_ERROR',

  // Facebook OAuth
  FACEBOOK_CODE_INVALID: 'FACEBOOK_CODE_INVALID',
  FACEBOOK_CODE_EXPIRED: 'FACEBOOK_CODE_EXPIRED',
  FACEBOOK_NOT_CONFIGURED: 'FACEBOOK_NOT_CONFIGURED',
  FACEBOOK_EMAIL_NOT_VERIFIED: 'FACEBOOK_EMAIL_NOT_VERIFIED',
  FACEBOOK_API_ERROR: 'FACEBOOK_API_ERROR',

  // User Self-Service
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  SAME_PASSWORD: 'SAME_PASSWORD',
  CANNOT_REVOKE_CURRENT_SESSION: 'CANNOT_REVOKE_CURRENT_SESSION',
  ADMIN_CANNOT_DEACTIVATE_SELF: 'ADMIN_CANNOT_DEACTIVATE_SELF',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',

  // Password Reset
  NO_PENDING_PASSWORD_RESET: 'NO_PENDING_PASSWORD_RESET',
  PASSWORD_RESET_CODE_EXPIRED: 'PASSWORD_RESET_CODE_EXPIRED',
  PASSWORD_RESET_CODE_INVALID: 'PASSWORD_RESET_CODE_INVALID',
  USER_NOT_FOUND_FOR_RESET: 'USER_NOT_FOUND_FOR_RESET',

  // Account Linking
  PROVIDER_ALREADY_LINKED: 'PROVIDER_ALREADY_LINKED',
  PROVIDER_LINKED_TO_OTHER_ACCOUNT: 'PROVIDER_LINKED_TO_OTHER_ACCOUNT',
  EMAIL_MISMATCH_ON_LINK: 'EMAIL_MISMATCH_ON_LINK',
  CANNOT_UNLINK_LAST_PROVIDER: 'CANNOT_UNLINK_LAST_PROVIDER',
  PROVIDER_NOT_LINKED: 'PROVIDER_NOT_LINKED',

  // Permissions
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  INVALID_PERMISSION_FORMAT: 'INVALID_PERMISSION_FORMAT',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];

/**
 * Translation key prefix for error codes
 */
export const ERROR_CODE_TRANSLATION_PREFIX = 'errors.codes';

/**
 * Get the translation key for an error code
 * @param code - The error code from the API
 * @returns The translation key for the error message
 */
export function getErrorCodeTranslationKey(code: string): string {
  return `${ERROR_CODE_TRANSLATION_PREFIX}.${code}`;
}
